EmployeesDeskBook/Models/DeskBook/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace EmployeesDeskBook.Models.Default
{
    public class EmployeeViewModel
    {   
        public int Id { get; set; }

        [Display(Name = "Имя")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Поле обязательно для ввода")]
        [StringLength(20, ErrorMessage = "Превышено максимальное колличество вводимых символов ")]
        public string Name { get; set; }

        [Display(Name = "Фамилия")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Поле обязательно для ввода")]
        [StringLength(20, ErrorMessage = "Превышено максимальное колличество вводимых символов ")]
        public string Sername { get; set; }

        [Display(Name = "Возраст")]
        [Required(AllowEmptyStrings = false, ErrorMessage = " Поле обязательно для ввода")]
        [Range(1,30, ErrorMessage = "Введен не верный возраст")]
        public int Age { get; set; }

        [Display(Name = "Отдел")]
        [StringLength(20, ErrorMessage = "Превышено максимальное колличество вводимых символов ")]
        public string Departament { get; set; }

        [Display(Name = "Дата рождения")]
        [DataType(DataType.Date, ErrorMessage = "Введен не верный формат даты")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy}")]
        public DateTime BirthDate { get; set; }
    }
}

EmployeesDeskBook/Models/DeskBook/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;   

namespace EmployeesDeskBook.Models.Default
{
    public class IndexViewModel
    {
        public int? Id { get; set; }
    }
}

EmployeesDeskBook/Controllers/DeskBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EmployeesDeskBook.Models.Default;


namespace EmployeesDeskBook.Controllers
{
    public class DeskBookController : Controller
    {
        private List<EmployeeViewModel> _list = null;

        public DeskBookController()
        {
            _list = Db.getList();
        }


        public ActionResult Index(int? id)
        {
            return View(new IndexViewModel
            {
                Id = id 
            });
        }

        [HttpGet]
        public ActionResult Employees(int? id)
        {

            if(id.HasValue)
            {
                return View("Employee", _list.FirstOrDefault(x => x.Id == id));
            }
            else
            {
                return View(_list);
            }
    
        }
        
        [HttpGet]
        public ActionResult CreateEmployee()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateEmployee(EmployeeViewModel employee)
        {
           
            if (!ModelState.IsValid)
            {
                return View("CreateEmployee", employee);
            }
            employee.Id = _list.Count + 1;
            Db.AddEmployee(employee);
            return RedirectToAction("Employees");
        }

        [HttpGet]
        public ActionResult EditEmployee(int id)
        {
            return View(_list.FirstOrDefault(x => x.Id == id));
        }

        [HttpPost]
        public ActionResult EditEmployee(EmployeeViewModel employee)
        {
            if(!ModelState.IsValid)
            {
                return View("EditEmployee", employee);
            }
            Db.EditEmployee(employee);
            return RedirectToAction("Employees");
        }
    }
}

EmployeesDeskBook/Views/DeskBook/CreateEmployee.cshtml
@model EmployeesDeskBook.Models.Default.EmployeeViewModel

@{
    ViewBag.Title = "CreateEmployee";
}

<h2>CreateEmployee</h2>

@using (Html.BeginForm("CreateEmployee", "DeskBook", FormMethod.Post, new { @class = "form", id = "employeeForm", name = "employeeData" }))
{
    <table>
        <tr>
            <th>Name</th>
            <th>Sername</th>
            <th>Departament</th>
            <th>Age</th>
            <th>BirthDate</th>
        </tr>
        <tr>
            <td>
                <div>
                    @Html.LabelFor(x => x.Name)
                    @Html.TextBoxFor(x => x.Name)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.Name)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.Sername)
                    @Html.TextBoxFor(x => x.Sername)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.BirthDate)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.Departament)
                    @Html.TextBoxFor(x => x.Departament)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.Departament)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.Age)
                    @Html.TextBoxFor(x => x.Age)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.Age)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.BirthDate)
                    @Html.TextBoxFor(x => x.BirthDate)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.BirthDate)
                </div>
            </td>
        <tr>
            <td>
                <input type="submit" value="Создать пользователя" />
            </td>
        </tr>

    </table>
}

EmployeesDeskBook/Views/DeskBook/EditEmployee.cshtml
@model EmployeesDeskBook.Models.Default.EmployeeViewModel

@{
    ViewBag.Title = $"Изменяем данные о сотруднике с ID {Model.Id}";
}

@using (Html.BeginForm("EditEmployee", "DeskBook", FormMethod.Post, new { @class = "form", id = "employeeForm", name = "employeeData" }))
{
    @Html.HiddenFor(x => x.Id)
    <table>
        <tr>
            <th>Name</th>
            <th>Sername</th>
            <th>Departament</th>
            <th>Age</th>
            <th>BirthDate</th>
        </tr>
        <tr>
            <td>
                <div>
                    @Html.LabelFor(x => x.Name)
                    @Html.TextBoxFor(x => x.Name)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.Name)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.Sername)
                    @Html.TextBoxFor(x => x.Sername)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.BirthDate)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.Departament)
                    @Html.TextBoxFor(x => x.Departament)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.Departament)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.Age)
                    @Html.TextBoxFor(x => x.Age)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.Age)
                </div>
            </td>
            <td>
                <div>
                    @Html.LabelFor(x => x.BirthDate)
                    @Html.TextBoxFor(x => x.BirthDate)
                </div>
                <div>
                    @Html.ValidationMessageFor(x => x.BirthDate)
                </div>
            </td>
            <tr>
                <td>
                    <input type="submit" value="Изменить" />
                </td>
            </tr>
    </table>
}

EmployeesDeskBook/Views/DeskBook/Employee.cshtml
@model EmployeesDeskBook.Models.Default.EmployeeViewModel

@{
    ViewBag.Title = "Employee";
}


@if (Model == null)
{
    <p>Сотрудник не наден</p>
}
else
{
    <table>
        <tr>
            <th>Name</th>
            <th>Sername</th>
            <th>Departament</th>
            <th>Age</th>
            <th>BirthDate</th>
        </tr>
        <tr>
            <td>@Html.DisplayFor(x => x.Name)</td>
            <td>@Html.DisplayFor(x => x.Sername)</td>
            <td>@Html.DisplayFor(x => x.Departament)</td>
            <td>@Html.DisplayFor(x => x.Age)</td>
            <td>@Html.DisplayFor(x => x.BirthDate)</td>
        </tr>
        <tr>
            <td>@Html.ActionLink("Вернуться назад", "Employees")</td>
        </tr>
    </table>
}

EmployeesDeskBook/Views/DeskBook/Employees.cshtml
@model List<EmployeesDeskBook.Models.Default.EmployeeViewModel>
@{
    ViewBag.Title = "Employees";
}

@if(!Model.Any())
{ 
    <div>
        Нет сотрудников
    </div>
}
else
{
   <div>
       <table>
           <tr>
               <th>Name</th>
               <th>Sername</th>
               <th>Departamnet</th>
               <th>Age</th>
           </tr>
           @foreach(var employee in Model)
           {
               <tr>
                   <td>@employee.Name</td>
                   <td>@employee.Sername</td>
                   <td>@employee.Departament</td>
                   <td>@employee.Age</td>
                   <td>@Html.ActionLink("Подробнее", "Employees", new { Id = employee.Id})</td>
                   <td>@Html.ActionLink("Редактировать", "EditEmployee", new { Id = employee.Id })</td>
               </tr>
      
           }
           <tr>
               <td>@Html.ActionLink("Создать нового пользователя", "CreateEmployee")</td>
           </tr>
       </table>
   </div>
}

EmployeesDeskBook/Views/DeskBook/Index.cshtml
@model EmployeesDeskBook.Models.Default.IndexViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    @if(Model.Id.HasValue)
    {
        <span>@Model.Id</span>
    }
    else
    {
        <span>Параметер Id не задан  </span>
    }
</div>

EmployeesDeskBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
</head>
<body>
    @RenderBody()
</body>
</html>